[package]
name = "goel-downloader"
version = "0.1.0"
authors = ["gogogoghost <491511934@qq.com>"]
edition = "2018"

[dependencies]

[dependencies.gtk]
version = "0.7.0"
features = ["v3_16"]

[dependencies.gio]
version = ""
features = ["v2_44"]